apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v9ve2obcd-dotnet-basic
  janus-idp.io/tekton: v9ve2obcd-dotnet-basic
  backstage.io/kubernetes-id: v9ve2obcd-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v9ve2obcd-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
